<HTML>
    <HEAD>
    <META NAME="Author" CONTENT="Crystal Reports 13.0">
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
        <style>    div {position:absolute; z-index:25}
            a {text-decoration:none}
            a img {border-style:none; border-width:0}
            .fc1id3qy1bes4yo-0 {font-size:17pt;color:#000000;font-family:Arial;font-weight:bold;}
            .fc1id3qy1bes4yo-1 {font-size:7pt;color:#000000;font-family:Arial;font-weight:normal;}
            .fc1id3qy1bes4yo-2 {font-size:9pt;color:#ffffff;font-family:Arial;font-weight:bold;}
            .fc1id3qy1bes4yo-3 {font-size:8pt;color:#000000;font-family:Arial;font-weight:normal;}
            .fc1id3qy1bes4yo-4 {font-size:11pt;color:#000000;font-family:Arial;font-weight:bold;}
            .fc1id3qy1bes4yo-5 {font-size:9pt;color:#000000;font-family:Arial;font-weight:normal;}
            .ad1id3qy1bes4yo-0 {border-color:#000000;border-left-width:0;border-right-width:0;border-top-width:0;border-bottom-width:0;}
        </style>
    </HEAD>
    <body style="width: 100%">
    <div style="z-index:10;top:168px;left:21px;width:747px;height:144px;border-color:#000000;border-style:solid;border-width:1px;"><table width="739px" height="136px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:357px;left:22px;width:747px;height:550px;border-color:#000000;border-style:solid;border-width:1px;"><table width="739px" height="542px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:143px;left:21px;width:746px;height:20px;border-color:#808080;border-style:solid;border-width:1px;background-color:#808080;layer-background-color:#808080;"><table width="739px" height="12px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:188px;left:46px;width:722px;height:20px;border-color:#000000;border-style:solid;border-width:1px;"><table width="715px" height="12px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:209px;left:46px;width:722px;height:20px;border-color:#000000;border-style:solid;border-width:1px;"><table width="715px" height="12px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:170px;left:48px;width:99px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:190px;left:48px;width:99px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:211px;left:48px;width:99px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:232px;left:48px;width:99px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:252px;left:48px;width:99px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:270px;left:48px;width:99px;height:39px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="31px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:379px;left:24px;width:95px;height:415px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="87px" height="407px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:271px;left:410px;width:97px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="89px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:293px;left:410px;width:97px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="89px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:378px;left:711px;width:57px;height:435px;border-color:#000000;border-style:solid;border-width:1px;"><table width="49px" height="427px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:415px;left:118px;width:650px;height:18px;border-color:#000000;border-style:solid;border-width:1px;"><table width="642px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:453px;left:118px;width:650px;height:18px;border-color:#000000;border-style:solid;border-width:1px;"><table width="642px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:491px;left:118px;width:650px;height:18px;border-color:#000000;border-style:solid;border-width:1px;"><table width="642px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:548px;left:118px;width:650px;height:18px;border-color:#000000;border-style:solid;border-width:1px;"><table width="642px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:530px;left:21px;width:747px;height:129px;border-color:#000000;border-style:solid;border-width:1px;"><table width="739px" height="121px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:604px;left:118px;width:650px;height:18px;border-color:#000000;border-style:solid;border-width:1px;"><table width="642px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:698px;left:118px;width:650px;height:18px;border-color:#000000;border-style:solid;border-width:1px;"><table width="642px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:250px;left:46px;width:722px;height:19px;border-color:#000000;border-style:solid;border-width:1px;"><table width="715px" height="11px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:10;top:211px;left:409px;width:99px;height:17px;border-color:#c0c0c0;border-style:solid;border-width:1px;background-color:#c0c0c0;layer-background-color:#c0c0c0;"><table width="91px" height="9px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:168px;left:46px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,146px,0px);height:146px;"><table width="0px" height="141px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:271px;left:408px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,43px,0px);height:43px;"><table width="0px" height="38px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:378px;left:118px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,455px,0px);height:455px;"><table width="0px" height="450px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:775px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:649px;"></div>
    <div style="z-index:15;top:291px;left:48px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:721px;"></div>
    <div style="z-index:15;top:271px;left:509px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,43px,0px);height:43px;"><table width="0px" height="38px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:168px;left:148px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,145px,0px);height:145px;"><table width="0px" height="140px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:210px;left:510px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,21px,0px);height:21px;"><table width="0px" height="16px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:210px;left:409px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,20px,0px);height:20px;"><table width="0px" height="15px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:15;top:378px;left:23px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:746px;"></div>
    <div style="z-index:15;top:397px;left:119px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:650px;"></div>
    <div style="z-index:15;top:585px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:650px;"></div>
    <div style="z-index:15;top:643px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:650px;"></div>
    <div style="z-index:15;top:679px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:650px;"></div>
    <div style="z-index:15;top:736px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:650px;"></div>
    <div style="z-index:15;top:757px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:650px;"></div>
    <div style="z-index:15;top:796px;left:23px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:747px;"></div>
    <div style="z-index:15;top:814px;left:120px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:649px;"></div>
    <div style="z-index:15;top:833px;left:119px;border-color:#000000;border-style:solid;border-width:0px;border-top-width:1px;width:649px;"></div>
    <div style="z-index:15;top:815px;left:651px;border-color:#000000;border-style:solid;border-width:0px;border-left-width:1px;clip:rect(0px,1px,18px,0px);height:18px;"><table width="0px" height="13px"><tr><td>&nbsp;</td></tr></table></div>
    <div style="z-index:3;clip:rect(0px,794px,133px,0px);top:0px;left:0px;width:794px;height:133px;"></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:80px;left:6px;width:743px;height:26px;"><table width="743px" border="0" cellpadding="0" cellspacing="0"><td align="center"><span class="fc1id3qy1bes4yo-0">EVALUACIÓN&nbsp;FINAL&nbsp;-&nbsp;VOLUNTARIO&nbsp;PRE&nbsp;PROFESIONAL</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:19px;left:289px;width:141px;height:58px;"><img src="{{ base_path() }}/public/img/reportes/evaluacion/logo.jpg" width="141px" height="58px"/></div>
    <div style="z-index:3;clip:rect(0px,794px,797px,0px);top:133px;left:0px;width:794px;height:797px;"></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:400px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Responsabilidad&nbsp;en&nbsp;el&nbsp;cumplimiento&nbsp;de&nbsp;las&nbsp;tareas&nbsp;asignadas</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:419px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Cumplimiento&nbsp;del&nbsp;horario&nbsp;de&nbsp;trabajo</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:437px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Cooperación&nbsp;ante&nbsp;cualquier&nbsp;tarea</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:381px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Cumplimiento&nbsp;de&nbsp;las&nbsp;normas&nbsp;de&nbsp;la&nbsp;BSPI</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:456px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Iniciativa,&nbsp;toma&nbsp;de&nbsp;decisiones&nbsp;y&nbsp;aporte&nbsp;de&nbsp;ideas</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:361px;left:230px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">EVALUACIÓN&nbsp;DE&nbsp;DESEMPEÑO</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:475px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Relaciones&nbsp;interpersonales</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:493px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Manejo&nbsp;del&nbsp;lenguaje&nbsp;oral&nbsp;y&nbsp;escrito</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:512px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Práctica&nbsp;de&nbsp;&nbsp;valores&nbsp;de&nbsp;ética,&nbsp;honestidad&nbsp;y&nbsp;respeto.</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:581px;left:26px;width:75px;height:25px;"><table width="75px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fc1id3qy1bes4yo-1">NIVEL&nbsp;DE&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">DESEMPEÑO</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:587px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Capacidad&nbsp;creativa</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:606px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Ejecución&nbsp;de&nbsp;las&nbsp;tareas&nbsp;encomendadas</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:627px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Capacidad&nbsp;recursiva</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:429px;left:26px;width:82px;height:52px;"><table width="82px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fc1id3qy1bes4yo-1">DISPOSICIÓN&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">ANTE&nbsp;EL&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">TRABAJO</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:644px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Actuación&nbsp;ante&nbsp;situaciones&nbsp;imprevistas</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:663px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Muestra&nbsp;dominio&nbsp;teórico-práctico&nbsp;en&nbsp;el&nbsp;área&nbsp;profesional</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:682px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Entrega&nbsp;oportuna&nbsp;de&nbsp;reportes&nbsp;al&nbsp;tutor</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:701px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Uso&nbsp;del&nbsp;lenguaje&nbsp;científico&nbsp;técnico</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:719px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Redacción&nbsp;y&nbsp;Ortografía</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:739px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Originalidad&nbsp;y&nbsp;Relevancia&nbsp;del&nbsp;trabajo&nbsp;realizado&nbsp;para&nbsp;la&nbsp;BSPI</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:758px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Adecuación&nbsp;a&nbsp;las&nbsp;exigencias&nbsp;de&nbsp;la&nbsp;BSPI</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:777px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Presentación&nbsp;de&nbsp;informe&nbsp;Final&nbsp;a&nbsp;Presidencia&nbsp;BSPI</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:670px;left:26px;width:75px;height:66px;"><table width="75px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fc1id3qy1bes4yo-1">CONOCIMIEN</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">TOS&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">TÉCNICOS</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:192px;left:49px;width:60px;height:15px;"><table width="60px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Código</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:213px;left:49px;width:60px;height:15px;"><table width="60px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Correo</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:213px;left:412px;width:84px;height:15px;"><table width="84px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Teléfono</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:253px;left:49px;width:84px;height:15px;"><table width="84px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Carrera</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:269px;left:49px;width:58px;height:26px;"><table width="58px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fc1id3qy1bes4yo-1">Período&nbsp;del&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">Voluntario</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:291px;left:49px;width:99px;height:21px;"><table width="99px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fc1id3qy1bes4yo-1">Unidad&nbsp;donde&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">realizó&nbsp;las&nbsp;pasantías</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:233px;left:49px;width:86px;height:15px;"><table width="86px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Universidad</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:269px;left:413px;width:93px;height:21px;"><table width="93px" border="0" cellpadding="0" cellspacing="0"><tr><td align="left"><span class="fc1id3qy1bes4yo-1">Total&nbsp;de&nbsp;horas&nbsp;del&nbsp;</span></td></tr><tr><td align="left"><span class="fc1id3qy1bes4yo-1">voluntario</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:296px;left:413px;width:86px;height:15px;"><table width="86px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Departamento</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:888px;left:39px;width:132px;height:15px;"><table width="132px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">FECHA&nbsp;DE&nbsp;EVALUACIÓN:&nbsp;</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:912px;left:686px;width:78px;height:15px;"><span class="fc1id3qy1bes4yo-1">{{ \Carbon\Carbon::now()->formatLocalized('%d de %B del %Y') }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:171px;left:51px;width:60px;height:15px;"><table width="60px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Nombre</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:870px;left:39px;width:43px;height:15px;"><table width="43px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">TUTOR:&nbsp;</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:147px;left:31px;width:218px;height:15px;"><table width="218px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-2">DATOS&nbsp;DEL&nbsp;VOLUNTARIO</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:233px;left:152px;width:477px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $voluntario->universidad !== null ? $voluntario->universidad->Nombre : $voluntario->Universidad }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:274px;left:513px;width:103px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $horas_voluntario }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:295px;left:513px;width:253px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $departamento }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:172px;left:152px;width:485px;height:15px;"><span class="fc1id3qy1bes4yo-4">{{ $voluntario->Nombres}}&nbsp;{{ $voluntario->Apellidos}}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:192px;left:152px;width:59px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $voluntario->id }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:213px;left:152px;width:258px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $voluntario->Correo }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:213px;left:512px;width:194px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $voluntario->Telefono }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:253px;left:152px;width:480px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $carrera }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:273px;left:152px;width:253px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $periodo_voluntario }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:296px;left:152px;width:253px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ $unidad }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:532px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Manejo&nbsp;de&nbsp;métodos,&nbsp;procedimientos&nbsp;y&nbsp;técnicas&nbsp;de&nbsp;trabajo</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:551px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Manejo&nbsp;y&nbsp;conservación&nbsp;de&nbsp;instrumentos&nbsp;y&nbsp;herramientas&nbsp;de&nbsp;trabajo</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:569px;left:126px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">Planificación&nbsp;y&nbsp;organización&nbsp;de&nbsp;las&nbsp;tareas</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:381px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt1 : $evaluacion->txt1 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:400px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt2 : $evaluacion->txt2 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:420px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt3 : $evaluacion->txt3 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:437px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt4 : $evaluacion->txt4 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:455px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt5 : $evaluacion->txt5 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:474px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt6 : $evaluacion->txt6 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:494px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt7 : $evaluacion->txt7 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:514px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt8 : $evaluacion->txt8 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:532px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt9 : $evaluacion->txt9 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:550px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt10 : $evaluacion->txt10 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:568px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt11 : $evaluacion->txt11 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:588px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt12 : $evaluacion->txt12 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:607px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt13 : $evaluacion->txt13 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:626px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt14 : $evaluacion->txt14 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:645px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt15 : $evaluacion->txt15 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:662px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt16 : $evaluacion->txt16 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:682px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt17 : $evaluacion->txt17 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:701px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt18 : $evaluacion->txt18 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:720px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt19 : $evaluacion->txt19 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:740px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt20 : $evaluacion->txt20 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:760px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt21 : $evaluacion->txt21 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:779px;left:716px;width:48px;height:15px;text-align:right;"><table width="48px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ $periodo != null ? $periodo->evaluacion->txt22 : $evaluacion->txt22 }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:800px;left:303px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">CALIFICACIÓN&nbsp;GLOBAL</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:799px;left:716px;width:49px;height:15px;text-align:right;"><table width="49px" border="0" cellpadding="0" cellspacing="0"><tr><td align="right"><span class="fc1id3qy1bes4yo-5">{{ round($calificacion_global,2) }}</span></td></tr></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:818px;left:303px;width:344px;height:15px;"><table width="344px" border="0" cellpadding="0" cellspacing="0"><td align="left"><span class="fc1id3qy1bes4yo-1">DESEMPEÑO</span></td></table></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:817px;left:658px;width:79px;height:15px;"><span class="fc1id3qy1bes4yo-5">{{ $desempenio}}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:887px;left:177px;width:133px;height:15px;"><span class="fc1id3qy1bes4yo-3">{{ \Carbon\Carbon::create($voluntario->periodo != null ? $voluntario->periodo->evaluacion->FechaIngreso : $voluntario->evaluacion->FechaIngreso)->format('d/m/Y') }}</span></div>
    <div class="ad1id3qy1bes4yo-0" nowrap="true" style="z-index:25;top:868px;left:88px;width:236px;height:15px;"><span class="fc1id3qy1bes4yo-5">{{ $tutor_info }}</span></div>
    
    <div id="pageNavigator" style="top:1123px;left:0px;font-style:italic;font-weight:100;font-size:smaller"> 
    <hr>
    </body>
    